# Basic information
homeassistant:
  name: Home
  # location
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_altitude
  # 
  unit_system: imperial
  time_zone: America/New_York
  # Customizations
  customize: !include customize.yaml

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

# HTTP server setup
http:
  base_url: !secret http_baseurl
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Sensors
sensor:
  # Weather prediction
  - platform: yr

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

# Z-Wave
zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret zwave_network_key

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
